### ISSUE TITLE
sklearn version issue for BayesianGausssianMixture 

### ISSUE THREAD

**Issue by saqib-sarwar** [Team-TUD/CTAB-GAN-Plus#1]
Hi @zhao-zilong 
Great work by you and your team.
I wanted to run the code but could not due to using the BayesianGausssianMixture from latest sklearn version. The problem is that there is an issue while installing the old sklearn version. So I wanted to work with the latest release of sklearn.

For that, can you kindly highlight what changes have been made in the BayesianGausssianMixture class from previous and current version, and how can I modify it in your code to successfully run the Adult dataset jupyter notebook. I searched for it, but found both the functions to be similar.

**Comment by zhao-zilong** [comment]
Hi @saqib-sarwar I updated the transformer.py file, could you try if it works now? the two versions have little difference, it should be good now.
