### ISSUE TITLE
Long time to generate synthetic data

### ISSUE THREAD

**Issue by oussamaRakye** [Team-TUD/CTAB-GAN-Plus#11]
Hello,

I have trained the model as follows with the original dataset containing 44k samples:
```
synthesizer = CTABGAN(raw_csv_path = real_path,
                 test_ratio = 0.2,
                 categorical_columns = categorical_columns,
                 log_columns = [],
                 mixed_columns= {},
                 general_columns = [],
                 non_categorical_columns = continuous_columns,
                 integer_columns = integer_columns,
                 problem_type= {"Classification": 'label'})
synthesizer.fit()
```
And generated samples with `synthesizer.generate_samples()`. 
 But after a few hours (approx 6h) it had only generated 192 out of 44727 samples. It has taken excessively long and I am wondering if I am doing anything wrong. I am using GTX 1050 Ti. I have also tried a GTX 2080 Ti for the same period (all I can tell is it didn't finish).

Thanks!

**Comment by zhao-zilong** [comment]
Hi @oussamaRakye ,

Yeah, it happens sometimes. That means your generation quality is not good and there are too many invalid generation. Check this response here and you can change the code accordingly: 
https://github.com/Team-TUD/CTAB-GAN-Plus/issues/7#issuecomment-1576690333

Zilong

**Comment by oussamaRakye** [comment]
Hello @zhao-zilong ,

Thanks! I will try the suggested changes from the post. Would retraining the model with more (or less) epochs help?

Oussama

**Comment by zhao-zilong** [comment]
Hi @oussamaRakye  yes, training more epochs could help.
