### ISSUE TITLE
Filling attribute gaps

### ISSUE THREAD

**Issue by ZhuTouG** [Team-TUD/CTAB-GAN-Plus#14]
Hi, if I have 10 feature attributes such as x1/x2/x3, can I customize x1 & x2 and then use CTABGAN+ to fill the remaining attributes?

**Comment by zhao-zilong** [comment]
Hi @ZhuTouG 

Sorry for the late reply, do you mean you want to use CTABGAN+ to achieve data imputation? In your training data, do you have x3? or you only have training data in x1 and x2？

Best,

Zilong

**Comment by zhao-zilong** [comment]
Hi again @ZhuTouG  if you want to achieve data imputation and data synthesis, I would suggest you to check our new code: https://github.com/zhao-zilong/Tabula which is based on large language models.
