### ISSUE TITLE
QUESTION FOR REGRESSION

### ISSUE THREAD

**Issue by chaotianshinaida** [Team-TUD/CTAB-GAN-Plus#15]
I want to know can CTAB-GAN+ generate data . Question1 The first column of my data is determined by the last thirteen columns.My data are all continuous data.When I input it into GTAN-GAN+ according to the king file, the program reports an error:
ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

Question2:Where in the code can you see that CTAB-GAN+ can solve not only classification problems but also regression problems?
I hope to get your reply, it's really important to me

**Comment by zhao-zilong** [comment]
Hi @chaotianshinaida  
I'm not sure if that is still the case. I think if you put your target column in the last column, then it should work. We take the last colume by default for the classifier/regressor.

And for where we defined the regressor, actually we still call it "classifier" in the paper, check this line of code: https://github.com/Team-TUD/CTAB-GAN-Plus/blob/ab07d3f1a3bd41ccdf72f9fef73ce3c704a9368d/model/synthesizer/ctabgan_synthesizer.py#L30 there is where when we have regression problem, we modified the last layer of the "classifier" to make it output only a number. We don't apply softmax in the logits anymore. 

Would you have a try and tell me if that works for you?

Best,

Zilong

**Comment by chaotianshinaida** [comment]
HELLO ，I tried again but the problem was not solved
![QQ截图20231210110358](https://github.com/Team-TUD/CTAB-GAN-Plus/assets/144888091/cce78cb4-9d89-4a3d-a6f3-64d86efade1a)
![QQ截图20231210110546](https://github.com/Team-TUD/CTAB-GAN-Plus/assets/144888091/bf14cd6f-6ef0-426d-8a5c-fd7925ffa69d)
![QQ截图20231210110718](https://github.com/Team-TUD/CTAB-GAN-Plus/assets/144888091/a4ec5415-d839-4197-bb10-918d656b9a76)

**Comment by chaotianshinaida** [comment]
![Uploading QQ截图20231210110514.png…]()

**Comment by chaotianshinaida** [comment]
my  target column in the last column now but it still report error like this. how to deal with this problem?

**Comment by chaotianshinaida** [comment]
![QQ截图20231210110358](https://github.com/Team-TUD/CTAB-GAN-Plus/assets/144888091/b7736266-20a4-4a2b-baa0-587deeb6f1a3)

**Comment by chaotianshinaida** [comment]
categorical_columns = [],
                 log_columns = [],
                 mixed_columns= {},
non_categorical_columns= []
 general_columns= ['A','B','B','C','D','E']
integer_columns = ['R','F']
problem_type= {"Regression": "N"]
YOU SEE,This is the part of the input data that I modified

**Comment by chaotianshinaida** [comment]
categorical_columns = [],
log_columns = [],
mixed_columns= {},
non_categorical_columns= []
general_columns= ['A','B','C','D','E']
integer_columns = ['R','F']
problem_type= {"Regression": "N"]
YOU SEE,This is the part of the input data that I modified

**Comment by chaotianshinaida** [comment]
This is an example in gothub, it doesn't work either
![Uploading QQ截图20231210112659.png…]()

**Comment by chaotianshinaida** [comment]
This is an example in github, it doesn't work either

**Comment by chaotianshinaida** [comment]
![Uploading QQ截图20231210112659.png…]()

**Comment by chaotianshinaida** [comment]
Thank you for your answer to my question.I modified it according to your request.
But new problems arise like this in picture. 
The error indicates a TypeError during the initialization of the BayesianGaussianMixture class at line 71 in the "E:\keyan\生成对抗神经网络\CTABGAN_PLUS_\CTAB-GAN-Plus-DP-main\model\synthesizer\transformer.py" file. Specifically, the __init__ method of the BayesianGaussianMixture class expects one positional argument, but during initialization, two positional arguments and five keyword-only arguments were provided. This suggests a discrepancy in the number or type of arguments being passed during the instantiation of the BayesianGaussianMixture object.

**Comment by chaotianshinaida** [comment]
![Uploading 初始化错误.png…]()

**Comment by chaotianshinaida** [comment]
Thank you very much for your answer, now the code works

**Comment by chaotianshinaida** [comment]
Hello author, I am very happy that I used CTAB-GAN+ to generate a set of data.
But there may still be some unresolved problems in the code that evaluates the data later.If you are free, I hope you can help me take a look
![pingguchucuo](https://github.com/Team-TUD/CTAB-GAN-Plus/assets/144888091/b5443632-f31f-4c61-945e-5e5001743c7e)

**Comment by chaotianshinaida** [comment]
Traceback (most recent call last):
  File "E:\keyan\生成对抗神经网络\CTAB_GAN_P\CTAB-GAN-Plus-main_\suanfaregression.py", line 32, in <module>
    result_mat = get_utility_metrics(real_path,fake_paths,"MinMax",model_dict, test_ratio = 0.20)
  File "E:\keyan\生成对抗神经网络\CTAB_GAN_P\CTAB-GAN-Plus-main_\model\eval\evaluation.py", line 57, in get_utility_metrics
    X_train_real, X_test_real, y_train_real, y_test_real = model_selection.train_test_split(data_real_X ,data_real_y, test_size=test_ratio, stratify=data_real_y,random_state=42) 
  File "D:\biancheng\Anaconda\anaconda\envs\ctabganplus\lib\site-packages\sklearn\utils\_param_validation.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "D:\biancheng\Anaconda\anaconda\envs\ctabganplus\lib\site-packages\sklearn\model_selection\_split.py", line 2670, in train_test_split
    train, test = next(cv.split(X=arrays[0], y=stratify))
  File "D:\biancheng\Anaconda\anaconda\envs\ctabganplus\lib\site-packages\sklearn\model_selection\_split.py", line 1746, in split
    for train, test in self._iter_indices(X, y, groups):
  File "D:\biancheng\Anaconda\anaconda\envs\ctabganplus\lib\site-packages\sklearn\model_selection\_split.py", line 2147, in _iter_indices
    raise ValueError(
ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

**Comment by chaotianshinaida** [comment]
I want to export the training set and test set. Which part of the code is this? And can your code modify the division ratio of the training set and the test set?

**Comment by zhao-zilong** [comment]
Hi @chaotianshinaida  

Sorry it takes some times to get back to you, I was quite busy last few days. Please check the new updates, it should fix all your bugs. It was a mistake, I didn't update the evaluation code for this repo for the regression dataset evaluation. Thanks for pointing out that.

Best,

Zilong

**Comment by chaotianshinaida** [comment]
Thank you I will try again
