### ISSUE TITLE
Licence for CTAB-GAN+

### ISSUE THREAD

**Issue by Yue-Qi7** [Team-TUD/CTAB-GAN-Plus#18]
We would like to release an open-source library for synthetic data generation, which includes CTAB-GAN+. However, we couldn't find any licence information for CTAB-GAN+. We are wondering if the licence for CTAB-GAN is also applicable to CTAB-GAN+. Thanks in advance!

**Comment by zhao-zilong** [comment]
@Yue-Qi7  yes, CTAB-GAN and CTAB-GAN+ are under the same license.

**Comment by Yue-Qi7** [comment]
Thank you so much!
