### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by iamamiramine** [Team-TUD/CTAB-GAN-Plus#20]
May I ask what Python version did you use to install the requirements and run your code?

**Comment by zhao-zilong** [comment]
Hi @iamamiramine  I forgot the exact python version when I released the code, but on my current python 3.10 system, it works.

**Comment by iamamiramine** [comment]
Thank you!
I tried with python 3.7 in a conda environment. Everything works fine except for sklearn. I used `pip install scikit-learn==0.24.1` instead of` sklearn==0.24.1`.

**Comment by Zehao-Zhang** [comment]
May I ask how you solve it?

**Comment by iamamiramine** [comment]
> Thank you! I tried with python 3.7 in a conda environment. Everything works fine except for sklearn. I used `pip install scikit-learn==0.24.1` instead of` sklearn==0.24.1`.

This is how i solved it
