### ISSUE TITLE
I want to add constraints to generate data. What should I do?

### ISSUE THREAD

**Issue by Lyy0617** [Team-TUD/CTAB-GAN-Plus#6]
I want to add constraints to generate data. What should I do?

**Comment by zhao-zilong** [comment]
Hi @Lyy0617  your question is too general, could you elaborate it more? What constraints do you want to implement on the generated data?

**Comment by Lyy0617** [comment]
Thank you very much for your reply. As my question needs a picture description, I give a detailed description of the problem on Attach file. I look forward to hearing from you again. @zhao-zilong 
[Question.docx](https://github.com/Team-TUD/CTAB-GAN-Plus/files/11584851/Question.docx)

**Comment by zhao-zilong** [comment]
@Lyy0617  I have read your document, here are my answers:
Q1: I don't think we can add that type of physics law here
Q2: check this line of code where we filter the generation before release the data: https://github.com/Team-TUD/CTAB-GAN-Plus/blob/6d72fda3a9f382339e55cb4b35befced4c1f3508/model/synthesizer/transformer.py#L330 if you don't want to have this limitation, you can have the generation out of bound.
Q3: To control the generation based on a given "continuous" value, now it is not supported by CTAB-GAN(+). We only train based on the mode of multi-gaussian-mixture, so roughly the local of the continuous value as the condition, not exactly the value.
