### ISSUE TITLE
Synthesis of data (with 107 columns and <100 rows) taking 4+ hours with no result , even with High GPU .

### ISSUE THREAD

**Issue by yash-rathore-arya** [Team-TUD/CTAB-GAN-Plus#7]
Dataset : https://drive.google.com/file/d/1NNn4rvijmrJnwb_D7-3KweOcqkv99-8j/view?usp=sharing : Lending Loan Club Dataset.
Colab nb link : https://drive.google.com/file/d/13HbGjE2eBEopGGwoasopKaUr5GCs6qvB/view?usp=sharing

STEPS Followed  :
1. Dividing cols into categorical and numerical cols , Even taking first 100 rows for training (not the whole dataset)
2. Changing sides as [4, 8, 16, 24, 32, 64, 128 ,256,512,1024] in line 378 and 385 of model/synthesizer/ctabgan_synthesizer.py
3. synthesizer = CTABGAN(
              raw_csv_path = real_path,
              test_ratio =  0.20,
              categorical_columns=cat,
              log_columns = [],
              mixed_columns= {},
              general_columns =[],
              non_categorical_columns = [],
              integer_columns=num,
              problem_type= {None:None}) 
              
**ISSUE : For first 100 row data , model.fit takes 35seconds , but model.generate samples takes INDEFINITE amount of time**

Tried Google Colab PRO , Paperspace A100-80G : 90gb ram , 12 cpu , 80 gpu as well. The model.generate_samples() codeline runs INDEFINITELY.

Please enlighten why this could be happening and what measures I can take to make this not happen for my code ASAP. 
Thanks in advance @zhao-zilong !

**Comment by zhao-zilong** [comment]
Hi @yash-rathore-arya  I encountered once your situation where generate_sample() takes infinite. That is because the generation quality is bad, and a lot of "invalid" generation is there. Maybe because the training is not totally converged. To solve is, check this line: https://github.com/Team-TUD/CTAB-GAN-Plus/blob/6d72fda3a9f382339e55cb4b35befced4c1f3508/model/synthesizer/transformer.py#L405

change
'''
return data_t[valid_ids],len(invalid_ids)
'''
to 
'''
return data_t,len(invalid_ids)
'''
should solve this problem.

**Comment by yash-rathore-arya** [comment]
I updated the code where you specified , but it still runs for a long time. synthesizer.generate_samples() should ideally take like 2-5 seconds to run. But even after the change it's been running for a solid 25 mins. Any other changes or ideas you might have ?
I can share with you the colab (editor permission) link if you wish to look at the issue closely. It's just a issue that model has been trained but it's not synthesizing.

**Comment by zhao-zilong** [comment]
25 mins for synthesising is indeed not normal, I think something is wrong there. I would like to help if you can share the colab. My email imzhaozilong@gmail.com

**Comment by yash-rathore-arya** [comment]
Thanks a lot for being proactive with this issue. I have sent you the Colab Link. You should've received the notification in your mail !

**Comment by zhao-zilong** [comment]
Hi @yash-rathore-arya  I just have a try on your dataset with the same setting of categorical and numerical columns as in your colab. If I only use first 100 rows, the training and sampling (about 0.2s) are all super fast. But when I use the whole dataset, it is too big for my machine (RTX 2080Ti), so I cannot train it. I checked the encoded data dimension it's 16000+, and with the conditional vector (also 16000+), I can imagine why the training is slow. But still, I don't know why the sampling is also slow, it shouldn't be. But one thing to keep in mind that when you call generate_sample(), it will generate the dataset the same size as your training data, so if you use the whole training dataset, the generate_sample() function should talk more time.

**Comment by zhao-zilong** [comment]
yeah, to add parameter to control number of generation, it can be done by adding a parameter here: https://github.com/Team-TUD/CTAB-GAN-Plus/blob/6d72fda3a9f382339e55cb4b35befced4c1f3508/model/ctabgan.py#L50

And again, as I ran your dataset with first 100 rows of data, I sent a capture screen to you, it's just 0.2s and the only change is as I mentioned above in this line: https://github.com/Team-TUD/CTAB-GAN-Plus/blob/6d72fda3a9f382339e55cb4b35befced4c1f3508/model/synthesizer/transformer.py#L405

**Comment by yash-rathore-arya** [comment]
Yupp it works. Thanks a lot !!
Will use the generate_samples() function to add my updation on it for number of generations.
Thanks again !
